version: '3.8'

services:
  aeroterrabot_dev:
    build: .
    volumes:
      - .:/workspace
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
    command: /bin/bash
